services:
  postgres:
    image: postgres:16
    container_name: cloudcart-postgres
    environment:
      POSTGRES_DB: cloudcartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - cloudcart-postgres-data:/var/lib/postgresql/data

  backend:
    build: ./cloudcart-backend
    container_name: cloudcart-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./cloudcart-frontend
    container_name: cloudcart-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  cloudcart-postgres-data: